# This workflow will do a clean installation of node dependencies, cache/restore them, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Electron Build CD

on:
  push:
    branches: [ "electron" ]

jobs:
  build-ionic:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
    - run: npm install
    - run: npm i @capacitor-community/electron
    - run: npm install -g electron
    - run: npm install -g @ionic/cli
    - run: ionic build
    - run: npx cap add @capacitor-community/electron
    - run: npx cap sync
    - run: cd electron && npm run electron:pack
    - run: ls electron
